apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: vp-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: vp-sa
  namespace: default

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: vp-sa
  namespace: default
